
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./mysql_data:/var/lib/mysql

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wp-install.sh:/tmp/wp-install.sh
      - ./www:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db



volumes:
  mysql_data: